---
title: "Master CHA1-3 Combined"
date: "2024-06-20"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This setup is commonly used at the beginning of an R Markdown document to configure global settings for code chunks, ensuring consistent behavior throughout the document.

```{r message=FALSE, warning=FALSE}
install.packages(c("rvest", "httr", "stringr"))
install.packages("RSelenium")
install.packages("webdriver")
install.packages("chromedriver")

library(tidyverse)
library(rio)
library(janitor)
library(dplyr)
library(rvest) 
library(httr) 
library(stringr)
library(RSelenium)

```

```{r}
CHA_2020_4 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2020Q4") %>% 
  mutate(quarter="2020Q4") %>% 
  clean_names()

CHA_2021_1 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2021Q1") %>% 
  mutate(quarter="2021Q1") %>% 
  clean_names()

CHA_2021_2 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2021Q2") %>% 
  mutate(quarter="2021Q2") %>% 
  clean_names()

CHA_2021_3 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2021Q3") %>% 
  mutate(quarter="2021Q3") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2021_4 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2021Q4") %>% 
  mutate(quarter="2021Q4") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2022_1 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2022Q1") %>% 
  mutate(quarter="2022Q1") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2022_2 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2022Q2") %>% 
  mutate(quarter="2022Q2") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2022_3 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2022Q3") %>% 
  mutate(quarter="2022Q3") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2022_4 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2022Q4") %>% 
  mutate(quarter="2022Q4") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2023_1 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2023Q1") %>% 
  mutate(quarter="2023Q1") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2023_2 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2023Q2") %>% 
  mutate(quarter="2023Q2") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2023_3 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2023Q3") %>% 
  mutate(quarter="2023Q3") %>% 
  clean_names() %>% 
  rename(vendor_id = vendor_i)

CHA_2023_4 <- rio::import("https://github.com/wellsdata/DJNF_Merrill/raw/main/data/CHA_Data_24_053R.xlsx", sheet = "2023Q4") %>% 
  mutate(quarter="2023Q4") %>% 
  clean_names() 
```

```{r}

CHA1 <- rbind(CHA_2020_4, CHA_2021_1, CHA_2021_2, CHA_2021_3, CHA_2021_4, CHA_2022_1, CHA_2022_2, CHA_2022_3, CHA_2022_4, CHA_2023_1, CHA_2023_2, CHA_2023_3, CHA_2023_4)

write.csv(CHA1,"CHA1.csv")
```

```{r}

CHA2_2019 <- import("CHA2(Jan2019-April2024).xlsx", sheet = "2019") %>% 
  mutate(year="2019") %>% 
  clean_names()

CHA2_2020 <- import("CHA2(Jan2019-April2024).xlsx", sheet = "2020") %>% 
  mutate(year="2020") %>% 
  clean_names()

CHA2_2021 <- import("CHA2(Jan2019-April2024).xlsx", sheet = "2021") %>% 
  mutate(year="2021") %>% 
  clean_names()

CHA2_2022 <- import("CHA2(Jan2019-April2024).xlsx", sheet = "2022") %>% 
  mutate(year="2022") %>% 
  clean_names()

CHA2_2023 <- import("CHA2(Jan2019-April2024).xlsx", sheet = "2023") %>% 
  mutate(year="2023") %>% 
  clean_names()

CHA2_2024 <- import("CHA2(Jan2019-April2024).xlsx", sheet = "2024 April") %>% 
  mutate(year="2024") %>% 
  clean_names()

CHA2 <- rbind(CHA2_2019, CHA2_2020, CHA2_2021, CHA2_2022, CHA2_2023, CHA2_2024)

CHA2$vendor_zip <- as.numeric(CHA2$vendor_zip)
CHA2$payment_month_number <- as.numeric(CHA2$payment_month_number)
CHA2$bedroom_size <- as.numeric(CHA2$bedroom_size)

write.csv(CHA2,"CHA2.csv")

colnames(CHA2)

summary(CHA2$vendor_address_line_1)

CHA2 %>% 
  count(vendor_address_line_1) %>% 
  arrange(desc(n)) %>% 
  head(10) 

#because there are multiple entries per month (grrrr), going to have to go with total payment amount to find any valuable data analysis 

sum(CHA2$payment_amount, na.rm = TRUE)
# [1] 2,867,739,566
mean(CHA2$payment_amount, na.rm = TRUE)
# 845.3352

vendors <- CHA2 %>% 
  select(vendor_name, vendor_address_line_1, payment_amount, year, zip) %>% 
  group_by(vendor_address_line_1) %>% 
  summarize(
    # vendor_name,
    # year,
    # zip,
    Total_Payment = sum(payment_amount, na.rm=TRUE), 
    Mean_Payment = mean(payment_amount, na.rm=TRUE),
    
    ) %>%  
  arrange(desc(Total_Payment))

#how much money each vendor receives from the CHA per year (yearly breakdown to find patterns over time)
vendors_year <- CHA2 %>% 
  select(vendor_name, vendor_address_line_1, payment_amount, year, zip) %>% 
  group_by(vendor_address_line_1, year) %>% 
  summarize(
    # vendor_name,
    # year,
    # zip,
    Total_Payment = sum(payment_amount, na.rm=TRUE), 
    Mean_Payment = mean(payment_amount, na.rm=TRUE),
    
    ) %>%  
  arrange(desc(Total_Payment))

# leases_per_owner <- CHA2 %>% 
#   count(vendor_name) %>% 
#   arrange(n) 
 

```

Zip codes extracted from CHA2 dataset

```{r}
# zip_list <- CHA2 %>% 
#   select(year, zip)%>% 
#   group_by(zip) 
# 
# CHA2 %>% 
#   count(zip) %>% 
#   arrange(n)

zip_list_per_year <- CHA2 %>% 
  mutate(zip = substr(zip, 1, 6)) %>%  # Extract first 6 digits of the zip code
  group_by(year, zip) %>%              # Group by year and the modified zip code
  summarise(count = n())               # Count occurrences

zip_list <- CHA2 %>% 
  mutate(zip = substr(zip, 1, 5)) %>%  # Extract first 6 digits of the zip code
  group_by(zip) %>%              # Group by year and the modified zip code
  summarise(count = n())

# # List of 86 ZIP codes from CHA2
# zip_codes <- c("60014", "60026", "60050", "60077", "60085", "60098", "60104",
#                "60155", "60201", "60302", "60409", "60411", "60419", "60422",
#                "60425", "60426", "60428", "60429", "60432", "60438", "60445",
#                "60458", "60465", "60471", "60473", "60478", "60601", "60602",
#                "60603", "60605", "60606", "60607", "60608", "60609", "60610",
#                "60611", "60612", "60613", "60614", "60615", "60616", "60617",
#                "60618", "60619", "60620", "60621", "60622", "60623", "60624",
#                "60625", "60626", "60628", "60629", "60630", "60631", "60632",
#                "60633", "60634", "60636", "60637", "60638", "60639", "60640",
#                "60641", "60642", "60643", "60644", "60645", "60646", "60647",
#                "60649", "60651", "60652", "60653", "60654", "60655", "60656",
#                "60657", "60659", "60660", "60661", "60707", "60803", "60805",
#                "60827")
#The Amount calulated per zip code is skewed because uneven amount of months per property and even entries per month (going to need to use CHA1 for zipcode breakdown per amount but will limit the time frame for data)
```

Census Tract HUV zip code data, filtered for the 86 zip codes from CHA2.

```{r}
Census_Zip_2019 <- import("Zipcode_2019 HCV Census .xlsx") %>% 
  clean_names()  

Census_Zip_2020 <- import("Zipcode_2020 HCV Census .xlsx") %>% 
  clean_names()

Census_Zip_2021 <- import("Zipcode_2021 HCV Census .xlsx") %>% 
  clean_names()

Census_Zip_2022 <- import("Zipcode_2022 HCV Census.xlsx") %>% 
  clean_names()

Census_Zip_2023 <- import("Zipcode_2023 HCV Census.xlsx") %>% 
  clean_names()

Census_Zip <- rbind(Census_Zip_2019, Census_Zip_2020, Census_Zip_2021, Census_Zip_2022, Census_Zip_2023) %>% 
  filter(program_label == "Housing Choice Vouchers") %>% 
  rename(zip_codes = entities) %>% 
  rename(date = quarter) %>% 
  select(date, zip_codes, program_label, total_units, people_per_unit, rent_per_month, hh_income, pct_disabled_all, pct_age62plus, pct_minority)
 
#Filter for the 86 zip codes --> analyze the census data

Census_Zip$zip_codes <- as.character(Census_Zip$zip_codes)

zip_codes_to_filter <- c("60014", "60026", "60050", "60077", "60085", "60098", 
                         "60104", "60155", "60201", "60302", "60409", "60411", 
                         "60419", "60422", "60425", "60426", "60428", "60429", 
                         "60432", "60438", "60445", "60458", "60465", "60471", 
                         "60473", "60478", "60601", "60602", "60603", "60605", 
                         "60606", "60607", "60608", "60609", "60610", "60611", 
                         "60612", "60613", "60614", "60615", "60616", "60617", 
                         "60618", "60619", "60620", "60621", "60622", "60623", 
                         "60624", "60625", "60626", "60628", "60629", "60630", 
                         "60631", "60632", "60633", "60634", "60636", "60637", 
                         "60638", "60639", "60640", "60641", "60642", "60643", 
                         "60644", "60645", "60646", "60647", "60649", "60651", 
                         "60652", "60653", "60654", "60655", "60656", "60657", 
                         "60659", "60660", "60661", "60707", "60803", "60805", 
                         "60827")

#data is a breakdown per year per zip (5 zips because 5 years)
Census_CHA_Zip <- Census_Zip %>%
  filter(zip_codes %in% zip_codes_to_filter) %>% 

#Total census data per zip code from 2019 to 2023
Census_CHA_Zip_Total <- Census_CHA_Zip %>% 
  group_by(zip_codes) %>% 
  summarize(
    Total_Units = sum(total_units, na.rm=TRUE), 
    People_per_Unit = sum(people_per_unit, na.rm=TRUE),
    Rent_per_month = sum(rent_per_month, na.rm=TRUE),
    HH_Income = sum(hh_income, na.rm=TRUE),
    Pct_Disabled_All = sum(pct_disabled_all, na.rm=TRUE),
    Pct_Age62Plus = sum(pct_age62plus, na.rm=TRUE),
    Pct_Minority = sum(pct_minority, na.rm=TRUE),
    
    )
  

  
#map it on flourish 

#write a draft (website) with the embedded data visuals and send as a draft

```


```{r}





```


